SynergineCoreBundle:
    resource: "@SynergineCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

login:
    pattern:   /login
    defaults:  { _controller: SynergineCoreBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout
